### PR TITLE
Add amp v0.mdj to csp

### PR DESCRIPTION
**Pull request by antiphoton**

### CODE REVIEW

**Comment by antiphoton** [comment]
The `go-vet` checks have been failing since the main branch commit [9bf70f26](https://github.com/ampproject/amppackager/commit/9bf70f26eea7bd1c1e1ba9de9ed36871e68d02aa)

**Review by twifkak — APPROVED** [review]
Addresses http://b/184281306.

Thanks! `go vet` failure is not blocking. I'll file a bug for it. I think there was even a draft fix for this somewhere.

**Comment by twifkak** [comment]
oh, oops

**Comment by twifkak** [comment]
I changed the target branch of the PR from `releases` to `master`. That is where it should land first, and only requires one approval.

**Comment by antiphoton** [comment]
Rebased from `master` and forced push.

**Comment by twifkak** [comment]
That fixes the `go vet` issue. :)

**Comment by twifkak** [comment]
I'll go ahead and "Squash and merge" per the Contributing instructions.

**Pull request merged**
