### PR TITLE
Sync from Google

### PR DESCRIPTION
**Pull request by Gregable**
This is an automatically generated pull request.

### CODE REVIEW

**Comment by Gregable** [comment]
The travis failure looks entirely unrelated to this PR. @twifkak any clue what's going on?

**Comment by twifkak** [comment]
```
	            	expected: "public, max-age=302399"
	            	actual  : "public, max-age=302398"
```

That's a known flake; test took a bit longer to run than usual. I'll close and reopen to trigger a new Travis run.

**Comment by twifkak** [comment]
Remember to rebase per https://github.com/ampproject/amppackager/wiki/Contributing#what-merge-type :)

**Comment by twifkak** [comment]
nvm, travis is happy, i'll do it

**Pull request merged**
